[build]
  functions = "netlify/functions"
  publish = "."   # keep this unless you have a separate build output folder

# optional: pretty path for the function
[[redirects]]
  from = "/api/jn-create-lead"
  to = "/.netlify/functions/jn-create-lead"
  status = 200
